#!/bin/ash
# BTRFS auto degraded initramfs hook

# hook name
: ${BTRFS_HOOK_NAME:="autodegraded"}

root_is_btrfs() {
    [ "$(blkid -s TYPE -o value "$root" )" != "btrfs" ] &&
        [ "$(blkid -s TYPE -o value -lt "$root" )" != "btrfs" ]
} 2>/dev/null

btrfs_mount_handler () {
    local x i=1 work=${1%/}
    BTRFS_DIR_WORK=${work}

    if ! root_is_btrfs; then
        default_mount_handler "$@"
        return
    fi

    # temporary mount btrfs root subvolume
    if ! mount -t btrfs -o subvolid=0,rw ${root} ${work}; then

        # try to mount in degraded mode
        if ${BTRFS_ENABLE_DEGRADED}; then
            if ! mount -t btrfs -o subvolid=0,rw,degraded ${root} ${work}; then
                btrfs_fatal "Unable to mount root subvolume in degraded mode"
                return 1
            else
                btrfs_warn "Mounted root subvolume in degraded mode"
                sleep 3
                rootflags="${rootflags},degraded"

                # supress rollback choice in degraded mode
                if ! ${BTRFS_ENABLE_DEGRADED_ROLLBACK}; then
                    btrfs_info "Disabled rollback feature in degraded mode"
                    kexeced=1
                fi
            fi
        else
            btrfs_fatal "Unable to mount root subvolume"
            return 1
        fi
    fi
    
}
