#!/bin/bash

build() {
    add_module btrfs
    add_binary btrfs
    add_binary btrfsck
    add_runscript
}

help() {
    cat <<HELPEOF
This hook provides support for multi-device btrfs root volumes to auto degraded.
if you install system on btrfs RAID1 and RAID10 system.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
