#!/bin/ash
# Copyright (c) 2014-2014, C yafengabc
# All rights reserved.
# BTRFS auto degraded initramfs hook
# This file is modified from mkinitcpio-btrfs, the original file copyright as follows:

# Copyright (c) 2010-2012, C Anthony Risinger
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met: 
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer. 
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution. 
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

run_hook () {

    if [ "$(blkid -s TYPE -o value "$root" )" != "btrfs" ] && [ "$(blkid -s TYPE -o value -lt "$root" )" != "btrfs" ]; then
        echo ":: The root filesystem is not btrfs return the default_mount"
        return
    fi
    
    # if the btrfs volume can't mount try scan it.
    if ! mount -t btrfs -o ${rootflags},rw ${root} /new_root; then
    	btrfs device scan
    else 
    	umount /new_root
    	return
    fi
    
    # temporary mount btrfs root subvolume
    if ! mount -t btrfs -o ${rootflags},rw ${root} /new_root; then
	echo "::Can't mount btrfs normaly!!!"
        # try to mount in degraded mode
        
            if ! mount -t btrfs -o ${rootflags},rw,degraded ${root} /new_root; then
                echo "::Unable to mount root subvolume in degraded mode!!!"
                return 1
            else
                echo -e "::Mounted root subvolume in degraded mode!"
                sleep 3
                rootflags="${rootflags},degraded"
            	umount /new_root
	    fi
   else
	umount /new_root
   fi
    
}
